<%@ include file="/WEB-INF/template/include.jsp"%>

<h2>Upload output generated by IRIS</h2>

<form method="post" enctype="multipart/form-data">
	<table>
		<tr>
			<td>Select output file</td>
			<td><input type="file" name="ivaoutputFile" /> <input type="submit" value='Upload' /> </td>
		</tr>
	</table>
</form>