ALTER TABLE  `iris_output_mapping` add(
  `creator` int(11) NOT NULL DEFAULT '1',
  `date_created` datetime NOT NULL,
  `changed_by` int(11) DEFAULT NULL,
  `date_changed` datetime DEFAULT NULL,
  `voided` tinyint(1) NOT NULL DEFAULT '0',
  `voided_by` int(11) DEFAULT NULL,
  `date_voided` datetime DEFAULT NULL,
  `void_reason` varchar(255) DEFAULT NULL,
  KEY `user_who_changed_iom` (`changed_by`),
  KEY `user_who_created_iom` (`creator`),
  KEY `user_who_voided_iom` (`voided_by`),
  CONSTRAINT `user_who_changed_iom` FOREIGN KEY (`changed_by`) REFERENCES `users` (`user_id`),
  CONSTRAINT `user_who_created_iom` FOREIGN KEY (`creator`) REFERENCES `users` (`user_id`),
  CONSTRAINT `user_who_voided_iom` FOREIGN KEY (`voided_by`) REFERENCES `users` (`user_id`)
) ;

SELECT p.patient_id AS ID,	
IF(datediff(CURDATE(), pr.birthdate)/365 >= 65, 'Y', 'N') AS ELDER	,
IF(datediff(CURDATE(), pr.birthdate)/365 >= 50 AND datediff(CURDATE(), pr.birthdate)/365 <= 64, 'Y', 'N') AS MIDAGE	,
IF(datediff(CURDATE(), pr.birthdate)/365 >= 15 AND datediff(CURDATE(), pr.birthdate)/365 <= 49, 'Y', 'N') AS ADULT	,
IF(datediff(CURDATE(), pr.birthdate)/365 >= 5 AND datediff(CURDATE(), pr.birthdate)/365 <= 14, 'Y', 'N') AS CHILD	,
IF(datediff(CURDATE(), pr.birthdate)/365 >= 1 AND datediff(CURDATE(), pr.birthdate)/365 <= 4, 'Y', 'N') AS UNDER5	,
IF(datediff(CURDATE(), pr.birthdate)/30.5 >= 1 AND datediff(CURDATE(), pr.birthdate)/30.5 <= 11, 'Y', 'N') AS INFANT	,
IF(datediff(CURDATE(), pr.birthdate) >= 28, 'Y', 'N') AS NEONATE	,
IF(pr.gender IN ('M', 'MALE'), 'Y', 'N') AS MALE	,
IF(pr.gender IN ('F', 'FEMALE'), 'Y', 'N')AS FEMALE	,
IF(datediff(CURDATE(), pr.birthdate)/365 >= 12 AND datediff(CURDATE(), pr.birthdate)/365 <= 19 AND pr.gender IN ('F', 'FEMALE'), 'Y', 'N') AS MAGEGP1	,
IF(datediff(CURDATE(), pr.birthdate)/365 >= 20 AND datediff(CURDATE(), pr.birthdate)/365 <= 34 AND pr.gender IN ('F', 'FEMALE'), 'Y', 'N')AS MAGEGP2	,
IF(datediff(CURDATE(), pr.birthdate)/365 >= 35 AND datediff(CURDATE(), pr.birthdate)/365 <= 49 AND pr.gender IN ('F', 'FEMALE'), 'Y', 'N')AS MAGEGP3	,
AS DIED_D1	,
AS DIED_D23,	
AS DIED_D36,	
AS DIED_W1	,
AS ACUTE	,
AS CHRONIC	,
AS SUDDEN	,
AS WET_SEAS,	
AS DRY_SEAS,	
AS HEART_DIS,	
AS TUBER	,
AS HIV_AIDS,	
AS HYPERT	,
AS DIABETES,	
AS ASTHMA	,
AS EPILEPSY,	
AS CANCER	,
AS COPD	,
AS DEMENT	,
AS DEPRESS	,
AS STROKE	,
AS SICKLE	,
AS KIDNEY_DIS,	
AS LIVER_DIS	,
AS MEASLES	,
AS MEN_CON	,
AS MENCON3	,
AS MALARIA	,
AS MALARNEG,	
AS FEVER	,
AS AC_FEVER,	
AS CH_FEVER,	
AS NIGHT_SW,	
AS COUGH	,
AS AC_COUGH,	
AS CH_COUGH,	
AS PR_COUGH,	
AS BL_COUGH,	
AS WHOOP	,
AS BREATH	,
AS RAPID_BR,	
AS AC_RPBR	,
AS CH_RPBR	,
AS BR_LESS	,
AS AC_BRL	,
AS CH_BRL	,
AS EXERT_BR,	
AS LYING_BR,	
AS CHEST_IN,	
AS WHEEZE	,
AS CH_PAIN	,
AS YELLOW	,
AS DIARR	,
AS AC_DIARR,	
AS PE_DIARR,	
AS CH_DIARR,	
AS BL_DIARR,	
AS VOMITING,	
AS BL_VOMIT,	
AS ABDOM	,
AS ABD_PAIN,	
AS AC_ABDP	,
AS CH_ABDP	,
AS SWE_ABD	,
AS AC_SWAB	,
AS CH_SWAB	,
AS ABD_MASS,	
AS AC_ABDM	,
AS CH_ABDM	,
AS HEADACHE,	
AS SKIN	,
AS SKIN_LES,	
AS SK_FEET	,
AS RASH	,
AS AC_RASH	,
AS CH_RASH	,
AS MEASRASH,	
AS HERPES	,
AS STIFF_NECK,	
AS AC_STNK	,
AS CH_STNK	,
AS COMA	,
AS CO_ONS	,
AS CONVUL	,
AS AC_CONV	,
AS CH_CONV	,
AS UNC_CON	,
AS URINE	,
AS URI_RET	,
AS EXC_URINE,	
AS URI_HAEM	,
AS WT_LOSS	,
AS WASTING	,
AS OR_CAND	,
AS RIGIDITY,	
AS SWELL	,
AS SWE_ORAL,	
AS SWE_NECK,	
AS SWE_ARMP,	
AS SWE_BREAST,	
AS SWE_GEN	,
AS SWE_OTH	,
AS SWE_LEGS,	
AS ANAEMIA	,
AS EXC_DRINK,	
AS HAIR	,
AS PARAL_ONE,	
AS EYE_SUNK	,
AS BL_ORIF	,
AS VB_BET	,
AS VB_MEN	,
AS VB_AFTER,	
AS DIFF_SW	,
AS NOT_PREG,	
AS PREGNANT,	
AS DEL_6WKS,	
AS PEND_6W	,
AS FIRST_P	,
AS MORE4	,
AS CS_PREV	,
AS MULTIP	,
AS LAB_24	,
AS DIED_LAB,	
AS DEATH_24,	
AS BABY_AL	,
AS BREAST_FD,	
AS DEL_FAC	,
AS DEL_HOME,	
AS DEL_ELSE,	
AS PROF_ASS,	
AS DEL_NORM,	
AS DEL_ASS	,
AS DEL_CS	,
AS BABY_POS,	
AS MON_EARLY,	
AS HYSTER	,
AS BPR_PREG,	
AS FIT_PREG,	
AS VIS_BL	,
AS BLEED	,
AS E_BLEED	,
AS S_BLEED	,
AS D_BLEED	,
AS P_BLEED	,
AS PLACENT_R,	
AS DISCH_SM	,
AS TERM_ATT	,
AS ABORT	,
AS BORN_EARLY,	
AS BORN_3437	,
AS BORN_38	,
AS AB_SIZE	,
AS BORN_SMALL,	
AS BORN_BIG	,
AS TWIN	,
AS COMDEL	,
AS CORD	,
AS WATERS	,
AS MOVE_LB	,
AS CYANOSIS,	
AS BABY_BR	,
AS BORN_NOBR,	
AS CRIED	,
AS NO_LIFE	,
AS MUSHY	,
AS FED_D1	,
AS ST_SUCK	,
AS AB_POSIT,	
AS CONV_D1	,
AS CONV_D2	,
AS ARCH_B	,
AS FONT_HI	,
AS FONT_LO	,
AS UNW_D1	,
AS UNW_D2	,
AS COLD	,
AS UMBINF	,
AS B_YELLOW,	
AS DEVEL	,
AS BORN_MALF,	
AS MLF_BK	,
AS MLF_LH	,
AS MLF_SH	,
AS MTTV	,
AS B_NORM	,
AS B_ASSIST,	
AS B_CAES	,
AS B_FIRST	,
AS B_MORE4	,
AS B_MBPR	,
AS B_MSMDS	,
AS B_MCON	,
AS B_MBVI	,
AS B_MVBL	,
AS B_BFAC	,
AS B_BHOME	,
AS B_BWAY	,
AS B_BPROF	,
AS INJURY	,
AS TRAFFIC	,
AS O_TRANS	,
AS FALL	,
AS DROWN	,
AS FIRE	,
AS ASSAULT	,
AS VENOM	,
AS FORCE	,
AS POISON	,
AS INFLICT	,
AS SUICIDE	,
AS ALCOHOL	,
AS SMOKING	,
AS MARRIED	,
AS VACCIN	,
AS TREAT	,
AS T_ORT	,
AS T_IV	,
AS BLOOD_TR,	
AS T_NGT	,
AS ANTIB_I	,
AS SURGERY	,
AS SUR_1M	,
AS DISCH	,
AS SHOSPF	,
AS STRANS	,
AS SADMIT	,
AS STREAT	,
AS SMEDIC	,
AS SMORE2	,
AS SDOUBT	,
AS STRADM	,
AS SMOBPH	,
AS SCOSTS 
FROM patient p JOIN encounter e ON p.patient_id = e.patient_id 
JOIN person pr ON p.patient_id = pr.person_id 
JOIN encounter_type et ON e.encounter_type = et.encounter_type_id AND et.name IN ('VA') 



ID	
ELDER	
MIDAGE	
ADULT	
CHILD	
UNDER5	
INFANT	
NEONATE	
MALE	
FEMALE	
MAGEGP1	
MAGEGP2	
MAGEGP3	
DIED_D1	
DIED_D23	
DIED_D36	
DIED_W1	
ACUTE	
CHRONIC	
SUDDEN	
WET_SEAS	
DRY_SEAS	
HEART_DIS	
TUBER	
HIV_AIDS	
HYPERT	
DIABETES	
ASTHMA	
EPILEPSY	
CANCER	
COPD	
DEMENT	
DEPRESS	
STROKE	
SICKLE	
KIDNEY_DIS	
LIVER_DIS	
MEASLES	
MEN_CON	
MENCON3	
MALARIA	
MALARNEG	
FEVER	
AC_FEVER	
CH_FEVER	
NIGHT_SW	
COUGH	
AC_COUGH	
CH_COUGH	
PR_COUGH	
BL_COUGH	
WHOOP	
BREATH	
RAPID_BR	
AC_RPBR	
CH_RPBR	
BR_LESS	
AC_BRL	
CH_BRL	
EXERT_BR	
LYING_BR	
CHEST_IN	
WHEEZE	
CH_PAIN	
YELLOW	
DIARR	
AC_DIARR	
PE_DIARR	
CH_DIARR	
BL_DIARR	
VOMITING	
BL_VOMIT	
ABDOM	
ABD_PAIN	
AC_ABDP	
CH_ABDP	
SWE_ABD	
AC_SWAB	
CH_SWAB	
ABD_MASS	
AC_ABDM	
CH_ABDM	
HEADACHE	
SKIN	
SKIN_LES	
SK_FEET	
RASH	
AC_RASH	
CH_RASH	
MEASRASH	
HERPES	
STIFF_NECK	
AC_STNK	
CH_STNK	
COMA	
CO_ONS	
CONVUL	
AC_CONV	
CH_CONV	
UNC_CON	
URINE	
URI_RET	
EXC_URINE	
URI_HAEM	
WT_LOSS	
WASTING	
OR_CAND	
RIGIDITY	
SWELL	
SWE_ORAL	
SWE_NECK	
SWE_ARMP	
SWE_BREAST	
SWE_GEN	
SWE_OTH	
SWE_LEGS	
ANAEMIA	
EXC_DRINK	
HAIR	
PARAL_ONE	
EYE_SUNK	
BL_ORIF	
VB_BET	
VB_MEN	
VB_AFTER	
DIFF_SW	
NOT_PREG	
PREGNANT	
DEL_6WKS	
PEND_6W	
FIRST_P	
MORE4	
CS_PREV	
MULTIP	
LAB_24	
DIED_LAB	
DEATH_24	
BABY_AL	
BREAST_FD	
DEL_FAC	
DEL_HOME	
DEL_ELSE	
PROF_ASS	
DEL_NORM	
DEL_ASS	
DEL_CS	
BABY_POS	
MON_EARLY	
HYSTER	
BPR_PREG	
FIT_PREG	
VIS_BL	
BLEED	
E_BLEED	
S_BLEED	
D_BLEED	
P_BLEED	
PLACENT_R	
DISCH_SM	
TERM_ATT	
ABORT	
BORN_EARLY	
BORN_3437	
BORN_38	
AB_SIZE	
BORN_SMALL	
BORN_BIG	
TWIN	
COMDEL	
CORD	
WATERS	
MOVE_LB	
CYANOSIS	
BABY_BR	
BORN_NOBR	
CRIED	
NO_LIFE	
MUSHY	
FED_D1	
ST_SUCK	
AB_POSIT	
CONV_D1	
CONV_D2	
ARCH_B	
FONT_HI	
FONT_LO	
UNW_D1	
UNW_D2	
COLD	
UMBINF	
B_YELLOW	
DEVEL	
BORN_MALF	
MLF_BK	
MLF_LH	
MLF_SH	
MTTV	
B_NORM	
B_ASSIST	
B_CAES	
B_FIRST	
B_MORE4	
B_MBPR	
B_MSMDS	
B_MCON	
B_MBVI	
B_MVBL	
B_BFAC	
B_BHOME	
B_BWAY	
B_BPROF	
INJURY	
TRAFFIC	
O_TRANS	
FALL	
DROWN	
FIRE	
ASSAULT	
VENOM	
FORCE	
POISON	
INFLICT	
SUICIDE	
ALCOHOL	
SMOKING	
MARRIED	
VACCIN	
TREAT	
T_ORT	
T_IV	
BLOOD_TR	
T_NGT	
ANTIB_I	
SURGERY	
SUR_1M	
DISCH	
SHOSPF	
STRANS	
SADMIT	
STREAT	
SMEDIC	
SMORE2	
SDOUBT	
STRADM	
SMOBPH	
SCOSTS